#----------------------------------------------------------------------
# plotcomparison.R
#----------------------------------------------------------------------
PlotComparison <- function(# Plot comparison for one or all countries from different runs.
  runname1, ##<< Run name of first set of results for comparison.
  runname2 = NULL, ##<< Run name of second set of results for comparison.
  runname3 = NULL, ##<< Run name of third set of results for comparison.
  runname4 = NULL, ##<< Run name of third set of results for comparison.
  isocompare.c = NULL, ##<< ISO country codes of countries to plot comparison for. If \code{NULL},
  ## use iso.c of first run.
  mcmc.meta = NULL, ##<< \code{mcmc.meta} object. Output from \code{\link{RunMCMC}}. 
  ## If \code{NULL}, defaults to \code{output.dir1/mcmc.meta}.
  weight.alpha.select1 = 0.5, ##<< Result type for first set: Value of \code{weight.alpha} for Bayesian melding.
  weight.alpha.select2 = 0.5, ##<< Result type for second set: Value of \code{weight.alpha} for Bayesian melding.
  weight.alpha.select3 = 0.5, ##<< Result type for third set: Value of \code{weight.alpha} for Bayesian melding.
  weight.alpha.select4 = 0.5, ##<< Result type for fourth set: Value of \code{weight.alpha} for Bayesian melding.
  output.dir1 = NULL, ##<< Directory where mcmc.meta and raw MCMC output are stored.
  ## If \code{NULL}, defaults to \code{output/runname1}, which is the default from \code{RunMCMC}).
  output.dir2 = NULL, ##<< Directory where mcmc.meta and raw MCMC output are stored.
  ## If \code{NULL}, defaults to \code{output/runname2}, which is the default from \code{RunMCMC}).
  output.dir3 = NULL, ##<< Directory where mcmc.meta and raw MCMC output are stored.
  ## If \code{NULL}, defaults to \code{output/runname3}, which is the default from \code{RunMCMC}).
  output.dir4 = NULL, ##<< Directory where mcmc.meta and raw MCMC output are stored.
  ## If \code{NULL}, defaults to \code{output/runname4}, which is the default from \code{RunMCMC}).
  legend1 = NULL, ##<< Legend for first set of results. If \code{NULL}, defaults to runname1.
  legend2 = NULL, ##<< Legend for second set of results. If \code{NULL}, defaults to runname2.
  legend3 = NULL, ##<< Legend for second set of results. If \code{NULL}, defaults to runname3.
  legend4 = NULL, ##<< Legend for second set of results. If \code{NULL}, defaults to runname4.
  legend.bty = "o", ##<< The type of box to be drawn around the legend. The allowed values are "o" (the default) and "n".
  year.start = NULL, ##<< Start year of estimates to plot. If \code{NULL}, earliest year of estimates available is used.
  year.end = NULL, ##<< End year of estimates to plot. If \code{NULL}, latest year of estimates available is used.
  indicator = NULL, ##<< Indicator type, used for y-axis label of plot.
  plot.igme = TRUE, ##<< Plot IGME estimates? If \code{TRUE}, load igme from \code{output.dir1/igme}.
  plot.defaultloess = FALSE, ##<< Plot default Loess estimates? If \code{TRUE}, load igme from \code{output.dir1/res_U5MR_IGMEdefault.rda}.
  plot.excluded = TRUE, ##<< Plot excluded observations and series?
  main.plot = TRUE, ##<< Include main plot?
  zoom = TRUE, ##<< Add zoom plot?
  zoom.year.start = 1990, ##<< First year of zoom range for zoom plot.
  zoom.year.end = 2017, ##<< Last year of zoom range for zoom plot.
  add.legend = TRUE, ##<< Add legend plot?
  separate.plots.by.country = FALSE, ##<< Separate plots generated by country?
  filename = NULL, ##<< Optional: Alternative file name for plots file.
  fig.dir = NULL, ##<< Directory to store plots. If \code{NULL}, defaults to folder \code{fig} in current working directory. 
  file.format = "pdf", ###add file format. current saving options: 1. png   2. pdf      Kai Zhong 05/22/2018
  indirect_series_visibility =T,    #####kai added an option whether to include indirect series   05/22/2018
  officialname=T,                    #####kai added an option whether to import official name   05/22/2018
  ...
) {
  if (is.null(output.dir1))
    output.dir1 <- file.path(getwd(), "output", runname1)
  if (is.null(legend1))
    legend1 <- runname1
  if (!is.null(runname2)) {
    if (is.null(output.dir2))
      output.dir2 <- file.path(getwd(), "output", runname2)
    if (is.null(legend2))
      legend2 <- runname2
  }
  if (!is.null(runname3)) {
    if (is.null(output.dir3))
      output.dir3 <- file.path(getwd(), "output", runname3)
    if (is.null(legend3))
      legend3 <- runname3
  }
  if (!is.null(runname4)) {
    if (is.null(output.dir4))
      output.dir4 <- file.path(getwd(), "output", runname4)
    if (is.null(legend4))
      legend4 <- runname4
  }
  if (is.null(mcmc.meta))
    load(file.path(output.dir1, "mcmc.meta.rda"))
  
  if(officialname==T){
    info <- read.csv(file.path(getwd(),"input/infoUNinclHIV.csv",sep=""), header = T, stringsAsFactors = F)
    officialname=as.data.frame(info)                    ###read in official country name    kai add 05/07/2018
    wuwu=data.frame(mcmc.meta$data.all$iso.c,stringsAsFactors=FALSE)
    #wawa=data.frame(mcmc.meta$data$iso.c,stringsAsFactors=FALSE)
    colnames(wuwu)="iso.c"
    #colnames(wawa)="iso.c"
    mcmc.meta$data.all$name.c=dplyr::left_join(wuwu,officialname,by="iso.c")$officialname.c
    mcmc.meta$data$name.c=dplyr::left_join(wuwu,officialname,by="iso.c")$officialname.c
    #mcmc.meta$data$name.c=dplyr::left_join(wawa,officialname,by="iso.c")$officialname.c    ###replace the old country name with the official country name    kai add 05/07/2018
  }
  
  if (is.null(fig.dir))
    fig.dir <- file.path(getwd(), "fig/")
  dir.create(fig.dir, showWarnings = FALSE)
  if (is.null(indicator))
    indicator <- mcmc.meta$settings$indicator.type
  load(file.path(output.dir1, "iso.c.rda"))
  iso.c1 <- iso.c
  load(file.path(output.dir1, "year.t.rda"))
  year.t1 <- year.t
  load(file.path(output.dir1, "res.cqt.Lw.rda"))
  res.cqt.Lw1 <- res.cqt.Lw
  res.cqt1 <- res.cqt.Lw1[[paste0(weight.alpha.select1)]]
  if (!is.null(runname2)) {
    load(file.path(output.dir2, "iso.c.rda"))
    iso.c2 <- iso.c
    load(file.path(output.dir2, "year.t.rda"))
    year.t2 <- year.t
    load(file.path(output.dir2, "res.cqt.Lw.rda"))
    res.cqt.Lw2 <- res.cqt.Lw
    res.cqt2 <- res.cqt.Lw2[[paste0(weight.alpha.select2)]]
  }
  if (!is.null(runname3)) {
    load(file.path(output.dir3, "iso.c.rda"))
    iso.c3 <- iso.c
    load(file.path(output.dir3, "year.t.rda"))
    year.t3 <- year.t
    load(file.path(output.dir3, "res.cqt.Lw.rda"))
    res.cqt.Lw3 <- res.cqt.Lw
    res.cqt3 <- res.cqt.Lw3[[paste0(weight.alpha.select3)]]
  }
  if (!is.null(runname4)) {
    load(file.path(output.dir4, "iso.c.rda"))
    iso.c4 <- iso.c
    load(file.path(output.dir4, "year.t.rda"))
    year.t4 <- year.t
    load(file.path(output.dir4, "res.cqt.Lw.rda"))
    res.cqt.Lw4 <- res.cqt.Lw
    res.cqt4 <- res.cqt.Lw4[[paste0(weight.alpha.select4)]]
  }
  if (is.null(isocompare.c))
    isocompare.c <- iso.c1
  if (plot.igme) {
    load(file = file.path(output.dir1, "igme.rda"))
  } else {
    igme <- NULL
  }
  
#   # change JR, 20131126
#   if (file.exists(file.path(output.dir1, "expypredict.ciq.rda")))
#     load(file = file.path(output.dir1, "expypredict.ciq.rda"))
  #----------------------------------------------------------------------
  resfinal.cqt <- res.cqt1
  if (!is.null(runname2)) {
    if (length(iso.c1) == 1) {
      resfinal.cqt2 <-array(dim=c(1,3,length(year.t1)),dimnames = list(iso.c1,c(0.05,0.5,0.95),year.t1))
      resfinal.cqt2[1, ,is.element(year.t1, year.t2) ] <- res.cqt2[match(iso.c1, iso.c2), , is.element(year.t2, year.t1)]
    } else {
      resfinal.cqt2 <- array(NA, c(length(iso.c1), 3, length(year.t1)))
      resfinal.cqt2[, , is.element(year.t1, year.t2)] <- 
        res.cqt2[match(iso.c1, iso.c2), , is.element(year.t2, year.t1)]
    }
  } else {
    resfinal.cqt2 <- NULL
  }
  if (!is.null(runname3)) {
    if (length(iso.c3) == 1) {
      resfinal.cqt3 <- array(NA, c(1, 3, length(year.t1)))
      resfinal.cqt3[1, , ] <- res.cqt3[match(iso.c1, iso.c3), , is.element(year.t3, year.t1)]
    } else {
      resfinal.cqt3 <- array(NA, c(length(iso.c1), 3, length(year.t1)))
      resfinal.cqt3[, , is.element(year.t1, year.t3)] <- 
        res.cqt3[match(iso.c1, iso.c3), , is.element(year.t3, year.t1)]
    }
  } else {
    resfinal.cqt3 <- NULL
  }
  if (!is.null(runname4)) {
    if (length(iso.c4) == 1) {
      resfinal.cqt4 <- array(NA, c(1, 3, length(year.t1)))
      resfinal.cqt4[1, , is.element(year.t1, year.t4)] <- res.cqt4[match(iso.c1, iso.c4), , is.element(year.t4, year.t1)] # revised by YS
    } else {
      resfinal.cqt4 <- array(NA, c(length(iso.c1), 3, length(year.t1)))
      resfinal.cqt4[, , is.element(year.t1, year.t4)] <- 
        res.cqt4[match(iso.c1, iso.c4), , is.element(year.t4, year.t1)]
    }
  } else {
    resfinal.cqt4 <- NULL
  }
  if (!is.null(year.start)) {
    if (year.start > min(year.t1)) {
      resfinal.cqt[, , year.t1 < year.start] <- NA
      if (!is.null(runname2))
        resfinal.cqt2[, , year.t1 < year.start] <- NA
      if (!is.null(runname3))
        resfinal.cqt3[, , year.t1 < year.start] <- NA
      if (!is.null(runname4))
        resfinal.cqt4[, , year.t1 < year.start] <- NA
    }
  }
  if (!is.null(year.end)) {
    if (year.end < max(year.t1)) {
      resfinal.cqt[, , year.t1 > year.end] <- NA
      if (!is.null(runname2))
        resfinal.cqt2[, , year.t1 > year.end] <- NA
      if (!is.null(runname3))
        resfinal.cqt3[, , year.t1 > year.end] <- NA
      if (!is.null(runname4))
        resfinal.cqt4[, , year.t1 > year.end] <- NA
    }
  }

  if (plot.defaultloess) {
    load(file = file.path(output.dir1, "res_U5MR_IGMEdefault.rda"))
    igme2 <- list()
    igme2$t <- res$igme$t
    igme2$iso.c <- iso.c1
    igme2$u.ct <- res$igme$u.ct[match(iso.c1, res$igme$iso.c), ]
    igme2$u.ct[is.na(resfinal.cqt[, 2, ])] <- NA # change JR, 20140421
    legend.igme2 <- "Default Loess"
  } else {
    igme2 <- legend.igme2 <- NULL
  }
  
  if (plot.excluded) {
    data.all <- mcmc.meta$data.all
  } else {
    data.all <- NULL
  }
  if(file.format=="png"){
    separate.plots.by.country=T             ######png file could only plot single country result
    print("file.format='png' will produce separate plots by country.")
  }
  
  plot.width <- (main.plot + zoom + add.legend)*7
  if (!separate.plots.by.country){
    if(file.format=="pdf"){
    pdf(file.path(fig.dir, paste0(ifelse(is.null(filename), 
                                         paste0("Results Comparison ", runname1, 
                                                ifelse(!is.null(runname2), paste0(" vs ", runname2), ""),
                                                ifelse(!is.null(runname3), paste0(" vs ", runname3), ""),
                                                ifelse(!is.null(runname4), paste0(" vs ", runname4), "")),
                                         filename),ifelse(indirect_series_visibility==F,"(some indirect data series omitted)",""), ".pdf")), 
        width = plot.width, height = 7)
    } 
  }
  for (c in (1:length(iso.c1))[is.element(iso.c1, isocompare.c)]) {
    if (separate.plots.by.country){
      if(file.format=="pdf"){
      pdf(file.path(fig.dir, paste0(ifelse(is.null(filename), 
                                           paste0("Results Comparison ", runname1, 
                                                  ifelse(!is.null(runname2), paste0(" vs ", runname2), ""),
                                                  ifelse(!is.null(runname3), paste0(" vs ", runname3), ""),
                                                  ifelse(!is.null(runname4), paste0(" vs ", runname4), "")),
                                           filename),mcmc.meta$data.all$iso.c[c],ifelse(indirect_series_visibility==F,"(some indirect data series omitted)",""), ".pdf")), 
          width = plot.width, height = 7)
      } else if(file.format=="png"){
            if((main.plot + zoom + add.legend)==3){
              png(file.path(fig.dir, paste0(ifelse(is.null(filename), 
                                                   paste0("Results Comparison ", runname1, 
                                                          ifelse(!is.null(runname2), paste0(" vs ", runname2), ""),
                                                          ifelse(!is.null(runname3), paste0(" vs ", runname3), ""),
                                                          ifelse(!is.null(runname4), paste0(" vs ", runname4), "")),
                                                   filename),mcmc.meta$data.all$iso.c[c],ifelse(indirect_series_visibility==F,"(some indirect data series omitted)",""), ".png")), width=24.75,height=8.25,units="in", res=250)
            } else if((main.plot + zoom + add.legend)==2){
              png(file.path(fig.dir, paste0(ifelse(is.null(filename), 
                                                   paste0("Results Comparison ", runname1, 
                                                          ifelse(!is.null(runname2), paste0(" vs ", runname2), ""),
                                                          ifelse(!is.null(runname3), paste0(" vs ", runname3), ""),
                                                          ifelse(!is.null(runname4), paste0(" vs ", runname4), "")),
                                                   filename),mcmc.meta$data.all$iso.c[c],ifelse(indirect_series_visibility==F,"(some indirect data series omitted)",""), ".png")), width=16.5,height=8.25,units="in", res=250)
            } else {png(file.path(fig.dir, paste0(ifelse(is.null(filename), 
                                                         paste0("Results Comparison ", runname1, 
                                                                ifelse(!is.null(runname2), paste0(" vs ", runname2), ""),
                                                                ifelse(!is.null(runname3), paste0(" vs ", runname3), ""),
                                                                ifelse(!is.null(runname4), paste0(" vs ", runname4), "")),
                                                         filename),mcmc.meta$data.all$iso.c[c],ifelse(indirect_series_visibility==F,"(some indirect data series omitted)",""), ".png")), width=8.25,height=8.25,units="in", res=250) }
      }
    }
    PlotDataAndEstimates(data = mcmc.meta$data,
                         data.all = data.all,
                         c = c,
                         est.years = year.t1,
                         ylab = indicator,
                         plot.se = TRUE,
                         CIs.cqt = resfinal.cqt,
                         CIs.tr.cqt = resfinal.cqt2,
                         CIs.iid.cqt = resfinal.cqt3,
                         #CIs2.cqt = resfinal.cqt2,
                         # newobsPIs.ciq = expypredict.ciq, # change JR, 20131126
                         legendfull = legend1,
                         legendtr = legend2,
                         legendiid = legend3,
                         legend2 = legend4,
                         legend.bty = legend.bty,
                         igme = igme,
                         igme2 = igme2,
                         main.plot = main.plot,
                         zoom = zoom,
                         zoom.year.start = zoom.year.start,
                         zoom.year.end = zoom.year.end,
                         add.legend = add.legend,
                         year.end=year.end) # add by YS, 201704
    if (separate.plots.by.country)
      dev.off()
  }
  if (!separate.plots.by.country)
    dev.off()
  cat(paste0("Comparison plots generated and saved to ", fig.dir, ".\n"))
  ##value<< NULL
  return(invisible())
}
