#----------------------------------------------------------------------
# plotresults.R
#----------------------------------------------------------------------
PlotResults <- function(# Plot results.
  ### Plot results, including priors and posteriors, country data and estimates, source type biases, country-specific
  ### variance.
  officialname=T, ###kai added a parameter here to import formal country name on 04/16/2018
  runname = "test", ##<< Run name.
  output.dir = NULL, ##<< Directory where mcmc.meta and raw MCMC output are stored.
  ## If \code{NULL}, defaults to \code{output/runname}, which is the default from \code{RunMCMC}).
  fig.dir = NULL, ##<< Directory to store plots. If \code{NULL}, defaults to folder \code{fig} in current working directory.
  estimates.file = NULL, ##<< UN IGME estimates file (median estimates only). If \code{NULL}, not plotted. 
  weight.alpha.select = 0.5, ##<< Result type: Value of \code{weight.alpha} for Bayesian melding.
  year.start = NULL, ##<< Start year of estimates to plot. If \code{NULL}, earliest year of estimates available is used.
  year.end = NULL, ##<< End year of estimates to plot. If \code{NULL}, latest year of estimates available is used.
  zoom.year.start = 1990,   ##<< Start year of estimates in zoom in plot. If \code{NULL}, latest year of estimates available is used.    Kai Zhong add 05/24/2018
  zoom.year.end = 2017.5,   ##<< End year of estimates in zoom in plot. If \code{NULL}, latest year of estimates available is used.      Kai Zhong add 05/24/2018
  percentiles = c(0.05,0.5,0.95), ##<< Percentiles.
  plot.results = TRUE,
  plot.model.parameters = TRUE,
  main.plot = TRUE, ##<< Include main plot?
  zoom = TRUE, ##<< Add zoomed plot?
  add.legend = TRUE, ##<< Add legend plot for data series?
  seriesnames.in.full = TRUE, ##<< Display series names in full? # change JR, 3 Sep 2013
  suppress.legend.plot1 = FALSE,
  suppress.legend.plot2 = FALSE,
  legend.bty = "o",
  cex.adj.factor = 1, ##<< Optional: Factor to adjust plot text size by.
  fig.dir.alt = NULL, ##<< Alternative directory for plots with different types plots in different folders.
  legendtext = NULL,  ###most recent curve legend name
  legend3=NULL,        ###most recent curve legend name
  legend4=NULL,        ###most recent curve legend name
  ## (Used for combined country-specific runs.)
  separate.plots.by.country = FALSE, ##<< Separate plots generated by country?
  file.format="pdf",
  hiv.removed = F,   #### show results with HIV deaths removed    Kai 09/26/2018
  indirect_series_visibility=T, #####kai added an option whether to include indirect series   05/22/2018
  wpp=NULL,   ###add wpp
  ihme=NULL,   ###add ihme
  completeihme=NULL
) {
  if (is.null(output.dir))
    output.dir <- file.path(getwd(), "output", runname)
  if (is.null(fig.dir))
    fig.dir <- file.path(getwd(), "fig/")
  dir.create(fig.dir, showWarnings = FALSE)
  if (!is.null(fig.dir.alt)) {
    dir.create(fig.dir.alt, showWarnings = FALSE)
    dir.create(file.path(fig.dir.alt, "Results"), showWarnings = FALSE)
    dir.create(file.path(fig.dir.alt, "Results (HIV-removed)"), showWarnings = FALSE)
  }
  load(file.path(output.dir, "mcmc.meta.rda"))
  
  
  if(officialname==T){
    info <- read.csv(file.path(getwd(),"input/infoUNinclHIV.csv",sep=""), header = T, stringsAsFactors = F)
    officialname=as.data.frame(info)                    ###read in official country name    kai add 05/07/2018
  wuwu=data.frame(mcmc.meta$data.all$iso.c,stringsAsFactors=FALSE)
  #wawa=data.frame(mcmc.meta$data$iso.c,stringsAsFactors=FALSE)
  colnames(wuwu)="iso.c"
  #colnames(wawa)="iso.c"
  mcmc.meta$data.all$name.c=dplyr::left_join(wuwu,officialname,by="iso.c")$officialname.c
  mcmc.meta$data$name.c=dplyr::left_join(wuwu,officialname,by="iso.c")$officialname.c
  #mcmc.meta$data$name.c=dplyr::left_join(wawa,officialname,by="iso.c")$officialname.c    ###replace the old country name with the official country name    kai add 05/07/2018
  }
  #mcmc.meta$data.all$source.Lc.s[[36]][1]="Encuesta Nacional de Salud y Nutricion "
  #mcmc.meta$data.all$source.Lc.s[[110]][1]="Demographic and Health Survey (Preliminary) "
  #load(file.path(output.dir, "mcmc.array.rda"))
  list2env(mcmc.meta$settings, envir = environment())
  hiv.file <- mcmc.meta$files$hiv.file
  # if (is.null(hiv.file))
  #   hiv.file <- file.path("input", paste0("dataUNAIDS_", indicator.type, ".csv"))
  # if (is.null(estimates.file))
  #   estimates.file <- file.path("input", paste0(indicator.type, "_un.csv"))
  
  if (plot.results) {
  load(file.path(output.dir, "iso.c.rda"))
  load(file.path(output.dir, "year.t.rda"))
  year.t.temp <- year.t
  if(hiv.removed == F){
    load(file.path(output.dir, "res.cqt.Lw.rda"))
    res.cqt <- res.cqt.Lw[[paste0(weight.alpha.select)]]
  } else {  
    load(file.path(output.dir, "res.hivremoved.cqt.Lw.rda")) 
    res.cqt <- res.hivremoved.cqt.Lw[[paste0(weight.alpha.select)]]      
    }    ####kai added 09/26/2018

  #load(file = file.path(output.dir, "resproject.list.c.rda"))
  #load(file = file.path(output.dir, "res.alpha.cp.rda"))
  if (file.exists(file.path(output.dir, "expypredict.ciq.rda")))
    load(file = file.path(output.dir, "expypredict.ciq.rda"))
  
  if (!is.null(year.start)) {
    if (year.start > min(year.t)) {
      res.cqt[, , year.t < year.start] <- NA
    }
  }
  if (!is.null(year.end)) {
    if (year.end < max(year.t)) {
      res.cqt[, , year.t > year.end] <- NA
    }
  }
  # load default loess
  if (file.exists(file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))) {
    load(file = file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))
    if (!is.null(year.start)) {
      if (year.start > min(res$igme$t)) {
        res$igme$u.ct[, res$igme$t < year.start] <- NA
      }
    }
    if (!is.null(year.end)) {
      if (year.end < max(res$igme$t)) {
        res$igme$u.ct[, res$igme$t > year.end] <- NA
      }
    }
  }

 
  #----------------------------------------------------------------------
  ##details<< Plot country data and fits using \code{\link{PlotDataAndEstimates}}.
  if (is.validation) {
    incompletevrobsandyears.Lc.i2 <- NULL
    excludedobsandyears.Lc.i2 <- mcmc.meta$data.val$excludedobsandyears.Lc.i2
  } else if (!is.null(mcmc.meta$jags.data$is.splinesabovevr.ci)) { # change JR, 20140501
    incompletevrobsandyears.Lc.i2 <- GetIncompleteVRObservationsAndYears(mcmc.meta = mcmc.meta)
    excludedobsandyears.Lc.i2 <- NULL
  } else {
    excludedobsandyears.Lc.i2 <- incompletevrobsandyears.Lc.i2 <- NULL
  }
  if (is.validation) {
    Ytr.c <- GetLastObservationYearInValidationTrainingSet(mcmc.meta = mcmc.meta)
    save(Ytr.c, file = file.path(output.dir, "Ytr.c.rda"))
  } else {
    Ytr.c <- NULL
  }
  if (!is.null(estimates.file)) {
    igme <- GetIGME(country.codes = mcmc.meta$data$iso.c,
                    # is.hiv.country = mcmc.meta$data$hiv.c,  
                    estimates.file = estimates.file,
                    hiv.file = hiv.file)
    save(igme, file = file.path(output.dir, "igme.rda"))
    cat("IGME estimates read in.\n")
  } else {
    igme <- NULL
  }
  ####read wpp and ihme data
  if(!is.null(wpp)){
    wpp=read.csv(wpp,stringsAsFactors = F, header=T) #read.csv(file.path(getwd(),"input/wpp.csv",stringsAsFactors = F, header=T))
  } else {wpp=NULL}
  if(!is.null(ihme)){
    countrynamelist=read.csv(file.path(getwd(),"input/country.info.CME.csv"))[,c(1,4)]
    countrylist=data.frame(country=countrynamelist[,1],iso=countrynamelist[,2])
    ihme=suppressWarnings(read_excel(ihme,col_names = F,col_types = "text",skip=3))
    colnames(ihme)=suppressWarnings(c("country","1970","1975","1980","1985","1990","1995","2000","2005","2010","2016"))
  } else {ihme=NULL}
  if(!is.null(completeihme)){
    countrynamelist=read.csv(file.path(getwd(),"input/country.info.CME.csv"))[,c(1,4)]
    countrylist=data.frame(country=countrynamelist[,1],iso=countrynamelist[,2])
    completeihme=read_excel(completeihme)
    #colnames(ihme)=suppressWarnings(c("country","1970","1975","1980","1985","1990","1995","2000","2005","2010","2016"))
  }
  wppihme=read_wpp_and_ihme(data=mcmc.meta$data,wpp=wpp,ihme=ihme,year.end=year.end,countrylist=countrylist)    #####create wpp and ihme array
  wpp_and_completeihme=read_wpp_and_completeihme(data=mcmc.meta$data,wpp=wpp,completeihme=completeihme,year.end=year.end,countrylist=countrylist)
  if (!is.null(estimates.file)) {
    igme <- GetIGME(country.codes = mcmc.meta$data$iso.c,
                    # is.hiv.country = mcmc.meta$data$hiv.c,  
                    estimates.file = estimates.file,
                    hiv.file = hiv.file)
    save(igme, file = file.path(output.dir, "igme.rda"))
    cat("IGME estimates read in.\n")
  } else {
    igme <- NULL
  }
  
  plot.width <- (main.plot + zoom + add.legend)*7     ####plot width is determined by whether three parts are included or not    kai added 05/13/2018
  plot.height <- 7
  if(file.format=="png"){
    separate.plots.by.country=T             ######png file could only plot single country result
    print("file.format='png' will produce separate plots by country.")
  }
  
  #####plot data only   kai 05/24/2018
  if (!separate.plots.by.country) {
    pdf(file = file.path(fig.dir, paste0(runname, " ", "Data",ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".pdf")), width = plot.width, height = 7)
  }
    for (c in 1:mcmc.meta$data.all$C){
      if (separate.plots.by.country){
        if(file.format=="png"){
          if((main.plot + zoom + add.legend)==3){
            png(file = file.path(fig.dir, paste0(runname, " Data ",  mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".png")), width=24.75,height=8.25,units="in", res=250)   ##when there are three parts in the plot   kai made changes 04/09/2018
          } else if((main.plot + zoom + add.legend)==2){png(file = file.path(fig.dir, paste0(runname, " Data ",  mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".png")), width=16.5,height=8.25,units="in", res=250)   ##when there are two random parts in the plot   kai made changes 04/09/2018
          } else {png(file = file.path(fig.dir, paste0(runname, " Data ",  mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".png")), width=8.25,height=8.25,units="in", res=250)}  ##when there is one random part in the plot   kai made changes 04/09/2018
        } else if(file.format=="pdf"){
          pdf(file = file.path(fig.dir, paste0(runname, " Data ",  mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".pdf")), width = plot.width , height = plot.height)   ##pdf width is determined by pdf.width which is given above     kai made changes 04/09/2018
        }
      }
      PlotDataAndEstimates(data = mcmc.meta$data,
                           data.all = mcmc.meta$data.all,
                           add.legend=add.legend,
                           main.plot=main.plot,
                           zoom=zoom,
                           zoom.year.start = zoom.year.start,    
                           zoom.year.end = zoom.year.end,
                           c = c,
                           indirect_series_visibility=indirect_series_visibility, #####kai added an option whether to include indirect series   05/22/2018
                           ylab = mcmc.meta$settings$indicator.type,
                           plot.se = TRUE,
                           year.end=year.end)
      if (separate.plots.by.country)
        dev.off()
    }
    if (!separate.plots.by.country)
      dev.off()
  cat("Country data plotted.\n")
  
  #####plot data and estimates   kai 05/24/2018
  if (!separate.plots.by.country) {
    if (is.null(fig.dir.alt)) {
      pdf(file = file.path(fig.dir, paste0(runname, " Results",ifelse(hiv.removed==T," (HIV removed)",""),ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""),".pdf")), width = plot.width , height = 7)    ##pdf width is determined by pdf.width which is given above    kai made changes 04/09/2018
    } else {
      pdf(file = file.path(fig.dir.alt, paste0(runname, " Results",ifelse(hiv.removed==T," (HIV removed)",""),ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""),".pdf")), width = plot.width , height = 7)    ##pdf width is determined by pdf.width which is given above    kai made changes 04/09/2018
    }
  }
  tryCatch(
  for (c in 1:mcmc.meta$data$C) {
    if (separate.plots.by.country){
      if(file.format=="png"){
        if((main.plot + zoom + add.legend)==3){
          png(file = file.path(fig.dir, paste0(runname, "_Results_", mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".png")), width=24.75,height=8.25,units="in", res=250)   ##when there are three parts in the plot   kai made changes 04/09/2018
        } else if((main.plot + zoom + add.legend)==2){png(file = file.path(fig.dir, paste0(runname, "_Results_",  mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".png")), width=16.5,height=8.25,units="in", res=250)   ##when there are two random parts in the plot   kai made changes 04/09/2018
        } else {png(file = file.path(fig.dir, paste0(runname, "_Results_",  mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".png")), width=8.25,height=8.25,units="in", res=250)}  ##when there is one random part in the plot   kai made changes 04/09/2018
      } else if(file.format=="pdf"){
        if(all(main.plot,zoom)==TRUE){
        pdf(file = file.path(fig.dir, paste0(runname, "_Results_", mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".pdf")), width = plot.width , height = 7)   ##pdf width is determined by pdf.width which is given above     kai made changes 04/09/2018
        } else {pdf(file = file.path(fig.dir, paste0(runname, "_Results_", mcmc.meta$data$iso.c[c],ifelse(indirect_series_visibility==F," (excl. SBH if FBH is available)",""), ".pdf")), width = plot.width , height = 7)}   ##pdf width is determined by pdf.width which is given above   kai made changes 04/09/2018
          }
      }
        PlotDataAndEstimates(data = mcmc.meta$data,
                         data.all = mcmc.meta$data.all,
                         c = c,
                         est.years = year.t,
                         ylab = indicator.type,
                         plot.se = TRUE,
                         CIs.cqt = res.cqt,
                         legendtext = legendtext,
                         # newobsPIs.ciq = expypredict.ciq, # change JR, 20131126
                         excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                         Ytr.c = Ytr.c,
                         #B.tk = resproject.list.c[[c]]$B.tk,
                         #alphayears.k = resproject.list.c[[c]]$alphayears.k,
                         #alpha.cp = res.alpha.cp,
                         #knots = resproject.list.c[[c]]$uyears.q.plot,
                         #u5.tj = u5.tj,
                         main.plot = main.plot,    ###show main plot or not     kai added 05/14/2018
                         zoom = zoom,    ###show "zoom in" or not      kai added 05/14/2018
                         zoom.year.start = zoom.year.start,    
                         zoom.year.end = zoom.year.end,
                         add.legend = add.legend,    ###legend included or not     kai added 05/14/2018
                         seriesnames.in.full = seriesnames.in.full,
                         suppress.legend.plot1 = suppress.legend.plot1,
                         suppress.legend.plot2 = suppress.legend.plot2,
                         legend.bty = legend.bty,
                         cex.adj.factor = cex.adj.factor,
                         #mfrow.suppress = TRUE,
                         igme = igme,
                         indirect_series_visibility=indirect_series_visibility,     #####kai added an option whether to include indirect series   05/22/2018
                         year.end=year.end,
                         wpp_and_ihme=wppihme,
                         wpp_and_completeihme=wpp_and_completeihme) # add by YS
    if (separate.plots.by.country)
      dev.off()
  },error=function(e){print(paste("country",c,"has a problem."))})
  if (!separate.plots.by.country)
    dev.off()
  cat("Country results plotted.\n")
  #----------------------------------------------------------------------  
 
  #----------------------------------------------------------------------
  if (!is.null(estimates.file)) { # plot only once if estimates.file not given, else this is a duplicate of Results plot
    if (!separate.plots.by.country) {
      if (is.null(fig.dir.alt)) {
        pdf(file = file.path(fig.dir, paste(runname, "Data with B3.pdf")), width = plot.width, height = 7)
      } else {
        pdf(file = file.path(fig.dir.alt, "Data with B3", paste(runname, "Data with B3.pdf")), 
            width = plot.width, height = 7)
      }
    }
    for (c in 1:mcmc.meta$data$C) {
      if (separate.plots.by.country)
        pdf(file = file.path(fig.dir, paste0(runname, " Data with B3_", mcmc.meta$data$iso.c[c], ".pdf")), 
            width = plot.width, height = 7)
      PlotDataAndEstimates(data = mcmc.meta$data,
                           data.all = mcmc.meta$data.all,
                           CIs.cqt = res.cqt,
                           legendfull = "B3",
                           c = c,
                           est.years = year.t,
                           ylab = indicator.type,
                           plot.se = TRUE,
                           excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                           main.plot = main.plot,
                           zoom = zoom,
                           add.legend = add.legend,
                           seriesnames.in.full = seriesnames.in.full,
                           suppress.legend.plot1 = suppress.legend.plot1,
                           suppress.legend.plot2 = suppress.legend.plot2,
                           legend.bty = legend.bty,
                           cex.adj.factor = cex.adj.factor)
      if (separate.plots.by.country)
        dev.off()
    }
    if (!separate.plots.by.country)
      dev.off()
    cat("Country data with B3 plotted.\n")
  }
  #----------------------------------------------------------------------
  if (file.exists(file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))) {
    if (!separate.plots.by.country) {
      if (is.null(fig.dir.alt)) {
        pdf(file = file.path(fig.dir, paste(runname, "Data with default Loess.pdf")), width = plot.width, height = 7)
      } else {
        pdf(file = file.path(fig.dir.alt, "Data with default Loess", paste(runname, "Data with default Loess.pdf")), 
            width = plot.width, height = 7)
      }
    }
    for (c in 1:mcmc.meta$data$C) {
      if (separate.plots.by.country)
        pdf(file = file.path(fig.dir, paste0(runname, " Data with default Loess_", mcmc.meta$data$iso.c[c], ".pdf")), 
            width = plot.width, height = 7)
      PlotDataAndEstimates(data = mcmc.meta$data,
                           data.all = mcmc.meta$data.all,
                           c = c,
                           est.years = year.t,
                           ylab = indicator.type,
                           plot.se = TRUE,
                           igme = res$igme,
                           legendigmemethod = "Default Loess",
                           excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                           main.plot = main.plot,
                           zoom = zoom,
                           add.legend = add.legend,
                           seriesnames.in.full = seriesnames.in.full,
                           suppress.legend.plot1 = suppress.legend.plot1,
                           suppress.legend.plot2 = suppress.legend.plot2,
                           legend.bty = legend.bty,
                           cex.adj.factor = cex.adj.factor)
      if (separate.plots.by.country)
        dev.off()
    }
    if (!separate.plots.by.country)
      dev.off()
    cat("Country data with default loess plotted.\n")
  }
  #----------------------------------------------------------------------
  if (file.exists(file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))) {
    if (!separate.plots.by.country) {
      if (is.null(fig.dir.alt)) {
        pdf(file = file.path(fig.dir, paste(runname, "Data with B3 & default Loess.pdf")), width = plot.width, height = 7)
      } else {
        pdf(file = file.path(fig.dir.alt, "Data with B3 & default Loess", paste(runname, "Data with default Loess.pdf")), 
            width = plot.width, height = 7)
      }
    }
    for (c in 1:mcmc.meta$data$C) {
      if (separate.plots.by.country)
        pdf(file = file.path(fig.dir, paste0(runname, " Data with B3 & default Loess_", mcmc.meta$data$iso.c[c], ".pdf")), 
            width = plot.width, height = 7)
      PlotDataAndEstimates(data = mcmc.meta$data,
                           data.all = mcmc.meta$data.all,
                           CIs.cqt = res.cqt,
                           legendfull = "B3",
                           c = c,
                           est.years = year.t,
                           ylab = indicator.type,
                           plot.se = TRUE,
                           igme = res$igme,
                           legendigmemethod = "Default Loess",
                           excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                           main.plot = main.plot,
                           zoom = zoom,
                           add.legend = add.legend,
                           seriesnames.in.full = seriesnames.in.full,
                           suppress.legend.plot1 = suppress.legend.plot1,
                           suppress.legend.plot2 = suppress.legend.plot2,
                           legend.bty = legend.bty,
                           cex.adj.factor = cex.adj.factor)
      if (separate.plots.by.country)
        dev.off()
    }
    if (!separate.plots.by.country)
      dev.off()
    cat("Country data with B3 default loess plotted.\n")
  }
  #----------------------------------------------------------------------
  ##details<< Plot country HIV-removed data and fits using \code{\link{PlotDataAndEstimates}}.
  }
  ##value<< NULL
  return(invisible())
}
#----------------------------------------------------------------------
GetIncompleteVRObservationsAndYears <- function(
  mcmc.meta ##<< ##<< \code{mcmc.meta} from \code{\link{RunMCMC}}.
) {
  incompletevrobsandyears.Lc.i2 <- list()
  for (c in 1:mcmc.meta$data$C) {
    if (is.null(mcmc.meta$data$isincompletevr.Lc.j[[c]])) {
      incompletevrobsandyears.Lc.i2[[c]] <- matrix(NA, 1, 2)
    } else {
      incompletevrobsandyears.Lc.i2[[c]] <- cbind(mcmc.meta$data$uvr.Lc.j[[c]][
        mcmc.meta$data$isincompletevr.Lc.j[[c]] == 1], 
        mcmc.meta$data$yearvr.Lc.j[[c]][
          mcmc.meta$data$isincompletevr.Lc.j[[c]] == 1])
    }
  }
  ##value<< List of matrices with 2 columns each, with the first column listing incomplete VR 
  ## observations and the second listing the observation years.
  return(incompletevrobsandyears.Lc.i2)
}
#----------------------------------------------------------------------
GetLastObservationYearInValidationTrainingSet <- function(# Get last observation year in training set 
  ### for validation exercise.
  mcmc.meta ##<< \code{mcmc.meta} from \code{\link{RunMCMC}}.
) {
  Ytr.c <- rep(NA, mcmc.meta$data$C)
  for(c in 1:mcmc.meta$data$C) {
    Ytr.c[c] <- max(mcmc.meta$jags.data$year.ci[c, mcmc.meta$data.val$geti.training.cj[
      c, !is.na(mcmc.meta$data.val$geti.training.cj[c, ])]])
  }
  ##value<< Vector of last observation year in training set for validation exercise.
  return(Ytr.c)
}
