#----------------------------------------------------------------------
# plotresults.R
#----------------------------------------------------------------------
PlotResults <- function(# Plot results.
  ### Plot results, including priors and posteriors, country data and estimates, source type biases, country-specific
  ### variance.
  runname = "test", ##<< Run name.
  output.dir = NULL, ##<< Directory where mcmc.meta and raw MCMC output are stored.
  ## If \code{NULL}, defaults to \code{output/runname}, which is the default from \code{RunMCMC}).
  fig.dir = NULL, ##<< Directory to store plots. If \code{NULL}, defaults to folder \code{fig} in current working directory.
  estimates.file = NULL, ##<< UN IGME estimates file (median estimates only). If \code{NULL}, not plotted. 
  weight.alpha.select = 0.5, ##<< Result type: Value of \code{weight.alpha} for Bayesian melding.
  year.start = NULL, ##<< Start year of estimates to plot. If \code{NULL}, earliest year of estimates available is used.
  year.end = NULL, ##<< End year of estimates to plot. If \code{NULL}, latest year of estimates available is used.
  percentiles = c(0.05,0.5,0.95), ##<< Percentiles.
  plot.results = TRUE,
  plot.model.parameters = TRUE,
  main.plot = TRUE, ##<< Include main plot?
  zoom = TRUE, ##<< Add zoomed plot?
  add.legend = TRUE, ##<< Add legend plot for data series?
  seriesnames.in.full = TRUE, ##<< Display series names in full? # change JR, 3 Sep 2013
  suppress.legend.plot1 = FALSE,
  suppress.legend.plot2 = FALSE,
  legend.bty = "o",
  cex.adj.factor = 1, ##<< Optional: Factor to adjust plot text size by.
  fig.dir.alt = NULL, ##<< Alternative directory for plots with different types plots in different folders.
  ## (Used for combined country-specific runs.)
  separate.plots.by.country = FALSE ##<< Separate plots generated by country?
) {
  if (is.null(output.dir))
    output.dir <- file.path(getwd(), "output", runname, "/")
  if (is.null(fig.dir))
    fig.dir <- file.path(getwd(), "fig/")
  dir.create(fig.dir, showWarnings = FALSE)
  if (!is.null(fig.dir.alt)) {
    dir.create(fig.dir.alt, showWarnings = FALSE)
    dir.create(file.path(fig.dir.alt, "Results"), showWarnings = FALSE)
    dir.create(file.path(fig.dir.alt, "Results (HIV-removed)"), showWarnings = FALSE)
  }
  
  load(file.path(output.dir, "mcmc.meta.rda"))
  load(file.path(output.dir, "mcmc.array.rda"))
  list2env(mcmc.meta$settings, envir = environment())
  hiv.file <- mcmc.meta$files$hiv.file
  # if (is.null(hiv.file))
  #   hiv.file <- file.path("input", paste0("dataUNAIDS_", indicator.type, ".csv"))
  # if (is.null(estimates.file))
  #   estimates.file <- file.path("input", paste0(indicator.type, "_un.csv"))
  
  if (plot.results) {
  load(file.path(output.dir, "iso.c.rda"))
  load(file.path(output.dir, "year.t.rda"))
  year.t.temp <- year.t
  load(file.path(output.dir, "res.cqt.Lw.rda"))
  res.cqt <- res.cqt.Lw[[paste0(weight.alpha.select)]]
  #load(file = file.path(output.dir, "resproject.list.c.rda"))
  #load(file = file.path(output.dir, "res.alpha.cp.rda"))
  
  if (file.exists(file.path(output.dir, "expypredict.ciq.rda")))#
    load(file = file.path(output.dir, "expypredict.ciq.rda"))#
  
  if (!is.null(year.start)) {
    if (year.start > min(year.t)) {
      res.cqt[, , year.t < year.start] <- NA
    }
  }
  if (!is.null(year.end)) {
    if (year.end < max(year.t)) {
      res.cqt[, , year.t > year.end] <- NA
    }
  }
  # load default loess
  if (file.exists(file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))) {
    load(file = file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))
    if (!is.null(year.start)) {
      if (year.start > min(res$igme$t)) {
        res$igme$u.ct[, res$igme$t < year.start] <- NA
      }
    }
    if (!is.null(year.end)) {
      if (year.end < max(res$igme$t)) {
        res$igme$u.ct[, res$igme$t > year.end] <- NA
      }
    }
  }

  plot.width <- (main.plot + zoom + add.legend)*7
  #----------------------------------------------------------------------
  ##details<< Plot country data and fits using \code{\link{PlotDataAndEstimates}}.
  if (is.validation) {
    incompletevrobsandyears.Lc.i2 <- NULL
    excludedobsandyears.Lc.i2 <- mcmc.meta$data.val$excludedobsandyears.Lc.i2
  } else if (!is.null(mcmc.meta$jags.data$is.splinesabovevr.ci)) { # change JR, 20140501
    incompletevrobsandyears.Lc.i2 <- GetIncompleteVRObservationsAndYears(mcmc.meta = mcmc.meta)
    excludedobsandyears.Lc.i2 <- NULL
  } else {
    excludedobsandyears.Lc.i2 <- incompletevrobsandyears.Lc.i2 <- NULL
  }
  if (is.validation) {
    Ytr.c <- GetLastObservationYearInValidationTrainingSet(mcmc.meta = mcmc.meta)
    save(Ytr.c, file = file.path(output.dir, "Ytr.c.rda"))
  } else {
    Ytr.c <- NULL
  }
  if (!is.null(estimates.file)) {
    igme <- GetIGME(country.codes = mcmc.meta$data$iso.c,
                    # is.hiv.country = mcmc.meta$data$hiv.c,  
                    estimates.file = estimates.file,
                    hiv.file = hiv.file)
    save(igme, file = file.path(output.dir, "igme.rda"))
    cat("IGME estimates read in.\n")
  } else {
    igme <- NULL
  }
  
  if (!separate.plots.by.country) {
    if (is.null(fig.dir.alt)) {
      pdf(file = file.path(fig.dir, paste(runname, "Results.pdf")), width = plot.width , height = 7)
    } else {
      pdf(file = file.path(fig.dir.alt, "Results", paste(runname, "Results.pdf")), width = plot.width , height = 7)
    }
  }
  for (c in 1:mcmc.meta$data$C) {
    if (separate.plots.by.country)
      pdf(file = file.path(fig.dir, paste0(runname, " Results_", mcmc.meta$data$iso.c[c], ".pdf")), width = plot.width , height = 7)
    PlotDataAndEstimates(data = mcmc.meta$data,
                         data.all = mcmc.meta$data.all,
                         c = c,
                         est.years = year.t,
                         ylab = indicator.type,
                         plot.se = TRUE,
                         CIs.cqt = res.cqt,
                         legendfull = "B3",
                         #newobsPIs.ciq = expypredict.ciq, # change JR, 20131126
                         excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                         Ytr.c = Ytr.c,
                         #B.tk = resproject.list.c[[c]]$B.tk,
                         #alphayears.k = resproject.list.c[[c]]$alphayears.k,
                         #alpha.cp = res.alpha.cp,
                         #knots = resproject.list.c[[c]]$uyears.q.plot,
                         #u5.tj = u5.tj,
                         main.plot = main.plot,
                         zoom = zoom,
                         #zoom.year.start = 1990,
                         #zoom.year.end = 2011,
                         add.legend = add.legend,
                         seriesnames.in.full = seriesnames.in.full,
                         suppress.legend.plot1 = suppress.legend.plot1,
                         suppress.legend.plot2 = suppress.legend.plot2,
                         legend.bty = legend.bty,
                         cex.adj.factor = cex.adj.factor,
                         #mfrow.suppress = TRUE,
                         igme = igme,
                         year.end=year.end) # add by YS
    if (separate.plots.by.country)
      dev.off()
  }
  if (!separate.plots.by.country)
    dev.off()
  cat("Country results plotted.\n")
  #----------------------------------------------------------------------  
  if (!separate.plots.by.country) {
    if (is.null(fig.dir.alt)) {
      pdf(file = file.path(fig.dir, paste(runname, "Data.pdf")), width = plot.width, height = 7)
    } else {
      pdf(file = file.path(fig.dir.alt, "Data", paste(runname, "Data.pdf")), width = plot.width, height = 7)
    }
  }
  for (c in 1:mcmc.meta$data$C) {
    if (separate.plots.by.country)
      pdf(file = file.path(fig.dir, paste0(runname, " Data_", mcmc.meta$data$iso.c[c], ".pdf")), width = plot.width, height = 7)
    PlotDataAndEstimates(data = mcmc.meta$data,
                         data.all = mcmc.meta$data.all,
                         c = c,
                         est.years = year.t,
                         ylab = indicator.type,
                         plot.se = TRUE,
                         excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                         main.plot = main.plot,
                         zoom = zoom,
                         add.legend = add.legend,
                         seriesnames.in.full = seriesnames.in.full,
                         suppress.legend.plot1 = suppress.legend.plot1,
                         suppress.legend.plot2 = suppress.legend.plot2,
                         legend.bty = legend.bty,
                         cex.adj.factor = cex.adj.factor,
                         year.end=year.end) # add by YS
    if (separate.plots.by.country)
      dev.off()
  }
  if (!separate.plots.by.country)
    dev.off()
  cat("Country data plotted.\n")
  #----------------------------------------------------------------------
  if (!is.null(estimates.file)) { # plot only once if estimates.file not given, else this is a duplicate of Results plot
    if (!separate.plots.by.country) {
      if (is.null(fig.dir.alt)) {
        pdf(file = file.path(fig.dir, paste(runname, "Data with B3.pdf")), width = plot.width, height = 7)
      } else {
        pdf(file = file.path(fig.dir.alt, "Data with B3", paste(runname, "Data with B3.pdf")), 
            width = plot.width, height = 7)
      }
    }
    for (c in 1:mcmc.meta$data$C) {
      if (separate.plots.by.country)
        pdf(file = file.path(fig.dir, paste0(runname, " Data with B3_", mcmc.meta$data$iso.c[c], ".pdf")), 
            width = plot.width, height = 7)
      PlotDataAndEstimates(data = mcmc.meta$data,
                           data.all = mcmc.meta$data.all,
                           CIs.cqt = res.cqt,
                           legendfull = "B3",
                           c = c,
                           est.years = year.t,
                           ylab = indicator.type,
                           plot.se = TRUE,
                           excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                           main.plot = main.plot,
                           zoom = zoom,
                           add.legend = add.legend,
                           seriesnames.in.full = seriesnames.in.full,
                           suppress.legend.plot1 = suppress.legend.plot1,
                           suppress.legend.plot2 = suppress.legend.plot2,
                           legend.bty = legend.bty,
                           cex.adj.factor = cex.adj.factor)
      if (separate.plots.by.country)
        dev.off()
    }
    if (!separate.plots.by.country)
      dev.off()
    cat("Country data with B3 plotted.\n")
  }
  #----------------------------------------------------------------------
  if (file.exists(file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))) {
    if (!separate.plots.by.country) {
      if (is.null(fig.dir.alt)) {
        pdf(file = file.path(fig.dir, paste(runname, "Data with default Loess.pdf")), width = plot.width, height = 7)
      } else {
        pdf(file = file.path(fig.dir.alt, "Data with default Loess", paste(runname, "Data with default Loess.pdf")), 
            width = plot.width, height = 7)
      }
    }
    for (c in 1:mcmc.meta$data$C) {
      if (separate.plots.by.country)
        pdf(file = file.path(fig.dir, paste0(runname, " Data with default Loess_", mcmc.meta$data$iso.c[c], ".pdf")), 
            width = plot.width, height = 7)
      PlotDataAndEstimates(data = mcmc.meta$data,
                           data.all = mcmc.meta$data.all,
                           c = c,
                           est.years = year.t,
                           ylab = indicator.type,
                           plot.se = TRUE,
                           igme = res$igme,
                           legendigmemethod = "Default Loess",
                           excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                           main.plot = main.plot,
                           zoom = zoom,
                           add.legend = add.legend,
                           seriesnames.in.full = seriesnames.in.full,
                           suppress.legend.plot1 = suppress.legend.plot1,
                           suppress.legend.plot2 = suppress.legend.plot2,
                           legend.bty = legend.bty,
                           cex.adj.factor = cex.adj.factor)
      if (separate.plots.by.country)
        dev.off()
    }
    if (!separate.plots.by.country)
      dev.off()
    cat("Country data with default loess plotted.\n")
  }
  #----------------------------------------------------------------------
  if (file.exists(file.path(output.dir, paste0("res_", indicator.type, "_IGMEdefault.rda")))) {
    if (!separate.plots.by.country) {
      if (is.null(fig.dir.alt)) {
        pdf(file = file.path(fig.dir, paste(runname, "Data with B3 & default Loess.pdf")), width = plot.width, height = 7)
      } else {
        pdf(file = file.path(fig.dir.alt, "Data with B3 & default Loess", paste(runname, "Data with default Loess.pdf")), 
            width = plot.width, height = 7)
      }
    }
    for (c in 1:mcmc.meta$data$C) {
      if (separate.plots.by.country)
        pdf(file = file.path(fig.dir, paste0(runname, " Data with B3 & default Loess_", mcmc.meta$data$iso.c[c], ".pdf")), 
            width = plot.width, height = 7)
      PlotDataAndEstimates(data = mcmc.meta$data,
                           data.all = mcmc.meta$data.all,
                           CIs.cqt = res.cqt,
                           legendfull = "B3",
                           c = c,
                           est.years = year.t,
                           ylab = indicator.type,
                           plot.se = TRUE,
                           igme = res$igme,
                           legendigmemethod = "Default Loess",
                           excludedobsandyears.Lc.i2 = excludedobsandyears.Lc.i2,
                           main.plot = main.plot,
                           zoom = zoom,
                           add.legend = add.legend,
                           seriesnames.in.full = seriesnames.in.full,
                           suppress.legend.plot1 = suppress.legend.plot1,
                           suppress.legend.plot2 = suppress.legend.plot2,
                           legend.bty = legend.bty,
                           cex.adj.factor = cex.adj.factor)
      if (separate.plots.by.country)
        dev.off()
    }
    if (!separate.plots.by.country)
      dev.off()
    cat("Country data with B3 default loess plotted.\n")
  }
  #----------------------------------------------------------------------
  ##details<< Plot country HIV-removed data and fits using \code{\link{PlotDataAndEstimates}}.
  # get results
  load(file = file.path(output.dir, "res.hivremoved.cqt.Lw.rda"))
  #if (!is.validation) {
  #  load(file = file.path(output.dir, "ypredict.hivremoved.ciq.rda"))
  #  exp.ypredict.hivremoved.ciq <- exp(ypredict.hivremoved.ciq)
  #} else {
  exp.ypredict.hivremoved.ciq <- NULL
  #}
  if (!is.null(estimates.file)) {
    igme.hivremoved <- GetIGME(country.codes = mcmc.meta$data$iso.c,
                               is.hiv.country = mcmc.meta$data$hiv.c,  
                               estimates.file = estimates.file,
                               hiv.file = hiv.file,
                               get.HIV.removed.data = TRUE)
    save(igme.hivremoved, file = file.path(output.dir, "igme.hivremoved.rda"))
  } else {
    igme.hivremoved <- NULL
  }
  if (sum(mcmc.meta$data$hiv.c) > 0) { # for HIV countries only
    if (is.null(fig.dir.alt)) {
      pdf(file = file.path(fig.dir, paste(runname, "Results plot (HIV-removed).pdf")), width = plot.width, height = 7)
    } else {
      pdf(file = file.path(fig.dir.alt, "Results (HIV-removed)", paste(runname, "Results plot (HIV-removed).pdf")), width = plot.width, height = 7)
    }
    for (c in (1:mcmc.meta$data$C)[mcmc.meta$data$hiv.c]){
      PlotDataAndEstimates(data = mcmc.meta$data.hivremoved,
                           data.all = mcmc.meta$data.hivremoved.all,
                           c = c,
                           est.years = year.t,
                           ylab = indicator.type,
                           plot.se = TRUE,
                           CIs.cqt = res.hivremoved.cqt.Lw[[paste0(weight.alpha.select)]],
                           newobsPIs.ciq = exp.ypredict.hivremoved.ciq,
                           igme = igme.hivremoved,
                           main.plot = main.plot,
                           zoom = zoom,
                           add.legend = add.legend,
                           seriesnames.in.full = seriesnames.in.full,
                           suppress.legend.plot1 = suppress.legend.plot1,
                           suppress.legend.plot2 = suppress.legend.plot2,
                           legend.bty = legend.bty,
                           cex.adj.factor = cex.adj.factor)
    }
    dev.off()
    cat("HIV-removed country results plotted.\n")
  }
  }
  
  if (plot.model.parameters) {
  #----------------------------------------------------------------------
  ##details<< Plot priors and posteriors using \code{\link{PlotPriorsAndPosteriors}}.
  PlotPriorsAndPosteriors(runname = runname, 
                          output.dir = output.dir, 
                          fig.dir = fig.dir)
  cat("Priors and posteriors plotted.\n")
  #----------------------------------------------------------------------
  ##details<< Plot source type prediction intervals using \code{\link{GenerateAndPlotSourceTypePIs}}.
  GenerateAndPlotSourceTypePIs(runname = runname, output.dir = output.dir, fig.dir = fig.dir,
                               recallperiod.R = c(5, 15), igme = 100, percentiles = percentiles,
                               plot.mean = FALSE, plot.type = "pdf")
  #----------------------------------------------------------------------
  ##details<< Plot model parameters using \code{\link{PlotCountrySmoothingParameters}}, 
  ## \code{\link{PlotCountryVarianceMultipliers}} and \code{\link{PlotDHSDirectBias}}.
  PlotCountrySmoothingParameters(runname = runname, output.dir = output.dir, 
                                 fig.dir = fig.dir, percentiles = percentiles)
  PlotCountryVarianceMultipliers(runname = runname, output.dir = output.dir, 
                                 fig.dir = fig.dir, percentiles = percentiles) 
  PlotDHSDirectBias(runname = runname, output.dir = output.dir, fig.dir = fig.dir, 
                    recall = seq(0, 20, 0.1))
  }
  ##value<< NULL
  return(invisible())
}
#----------------------------------------------------------------------
GetIncompleteVRObservationsAndYears <- function(
  mcmc.meta ##<< ##<< \code{mcmc.meta} from \code{\link{RunMCMC}}.
) {
  incompletevrobsandyears.Lc.i2 <- list()
  for (c in 1:mcmc.meta$data$C) {
    if (is.null(mcmc.meta$data$isincompletevr.Lc.j[[c]])) {
      incompletevrobsandyears.Lc.i2[[c]] <- matrix(NA, 1, 2)
    } else {
      incompletevrobsandyears.Lc.i2[[c]] <- cbind(mcmc.meta$data$uvr.Lc.j[[c]][
        mcmc.meta$data$isincompletevr.Lc.j[[c]] == 1], 
        mcmc.meta$data$yearvr.Lc.j[[c]][
          mcmc.meta$data$isincompletevr.Lc.j[[c]] == 1])
    }
  }
  ##value<< List of matrices with 2 columns each, with the first column listing incomplete VR 
  ## observations and the second listing the observation years.
  return(incompletevrobsandyears.Lc.i2)
}
#----------------------------------------------------------------------
GetLastObservationYearInValidationTrainingSet <- function(# Get last observation year in training set 
  ### for validation exercise.
  mcmc.meta ##<< \code{mcmc.meta} from \code{\link{RunMCMC}}.
) {
  Ytr.c <- rep(NA, mcmc.meta$data$C)
  for(c in 1:mcmc.meta$data$C) {
    Ytr.c[c] <- max(mcmc.meta$jags.data$year.ci[c, mcmc.meta$data.val$geti.training.cj[
      c, !is.na(mcmc.meta$data.val$geti.training.cj[c, ])]])
  }
  ##value<< Vector of last observation year in training set for validation exercise.
  return(Ytr.c)
}
